# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ProphetModel.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ProphetModel.proto',
  package='net.livemood.bdc.prophet.proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12ProphetModel.proto\x12\x1enet.livemood.bdc.prophet.proto\"0\n\x0cTimeSequence\x12\x11\n\tdate_time\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\"_\n\x0eProphetRequest\x12?\n\tsequences\x18\x01 \x03(\x0b\x32,.net.livemood.bdc.prophet.proto.TimeSequence\x12\x0c\n\x04\x66req\x18\x02 \x01(\t\"h\n\x08Response\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\x12=\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32/.net.livemood.bdc.prophet.proto.ProphetResponse\"u\n\x0fProphetResponse\x12\x11\n\tdate_time\x18\x01 \x01(\t\x12\x15\n\rforecastValue\x18\x02 \x01(\x01\x12\x1b\n\x13\x66orecastValue_lower\x18\x03 \x01(\x01\x12\x1b\n\x13\x66orecastValue_upper\x18\x04 \x01(\x01\x62\x06proto3'
)




_TIMESEQUENCE = _descriptor.Descriptor(
  name='TimeSequence',
  full_name='net.livemood.bdc.prophet.proto.TimeSequence',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='date_time', full_name='net.livemood.bdc.prophet.proto.TimeSequence.date_time', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='net.livemood.bdc.prophet.proto.TimeSequence.value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=102,
)


_PROPHETREQUEST = _descriptor.Descriptor(
  name='ProphetRequest',
  full_name='net.livemood.bdc.prophet.proto.ProphetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sequences', full_name='net.livemood.bdc.prophet.proto.ProphetRequest.sequences', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='freq', full_name='net.livemood.bdc.prophet.proto.ProphetRequest.freq', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=199,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='net.livemood.bdc.prophet.proto.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='net.livemood.bdc.prophet.proto.Response.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='code', full_name='net.livemood.bdc.prophet.proto.Response.code', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='net.livemood.bdc.prophet.proto.Response.data', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=201,
  serialized_end=305,
)


_PROPHETRESPONSE = _descriptor.Descriptor(
  name='ProphetResponse',
  full_name='net.livemood.bdc.prophet.proto.ProphetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='date_time', full_name='net.livemood.bdc.prophet.proto.ProphetResponse.date_time', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='forecastValue', full_name='net.livemood.bdc.prophet.proto.ProphetResponse.forecastValue', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='forecastValue_lower', full_name='net.livemood.bdc.prophet.proto.ProphetResponse.forecastValue_lower', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='forecastValue_upper', full_name='net.livemood.bdc.prophet.proto.ProphetResponse.forecastValue_upper', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=307,
  serialized_end=424,
)

_PROPHETREQUEST.fields_by_name['sequences'].message_type = _TIMESEQUENCE
_RESPONSE.fields_by_name['data'].message_type = _PROPHETRESPONSE
DESCRIPTOR.message_types_by_name['TimeSequence'] = _TIMESEQUENCE
DESCRIPTOR.message_types_by_name['ProphetRequest'] = _PROPHETREQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['ProphetResponse'] = _PROPHETRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TimeSequence = _reflection.GeneratedProtocolMessageType('TimeSequence', (_message.Message,), {
  'DESCRIPTOR' : _TIMESEQUENCE,
  '__module__' : 'ProphetModel_pb2'
  # @@protoc_insertion_point(class_scope:net.livemood.bdc.prophet.proto.TimeSequence)
  })
_sym_db.RegisterMessage(TimeSequence)

ProphetRequest = _reflection.GeneratedProtocolMessageType('ProphetRequest', (_message.Message,), {
  'DESCRIPTOR' : _PROPHETREQUEST,
  '__module__' : 'ProphetModel_pb2'
  # @@protoc_insertion_point(class_scope:net.livemood.bdc.prophet.proto.ProphetRequest)
  })
_sym_db.RegisterMessage(ProphetRequest)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'ProphetModel_pb2'
  # @@protoc_insertion_point(class_scope:net.livemood.bdc.prophet.proto.Response)
  })
_sym_db.RegisterMessage(Response)

ProphetResponse = _reflection.GeneratedProtocolMessageType('ProphetResponse', (_message.Message,), {
  'DESCRIPTOR' : _PROPHETRESPONSE,
  '__module__' : 'ProphetModel_pb2'
  # @@protoc_insertion_point(class_scope:net.livemood.bdc.prophet.proto.ProphetResponse)
  })
_sym_db.RegisterMessage(ProphetResponse)


# @@protoc_insertion_point(module_scope)
