# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ProphetService.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import service as _service
from google.protobuf import service_reflection
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import proto.ProphetModel_pb2 as ProphetModel__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ProphetService.proto',
  package='net.livemood.bdc.prophet.proto',
  syntax='proto3',
  serialized_options=b'\220\001\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14ProphetService.proto\x12\x1enet.livemood.bdc.prophet.proto\x1a\x12ProphetModel.proto2v\n\x0eProphetService\x12\x64\n\x08\x66orecast\x12..net.livemood.bdc.prophet.proto.ProphetRequest\x1a(.net.livemood.bdc.prophet.proto.ResponseB\x03\x90\x01\x01\x62\x06proto3'
  ,
  dependencies=[ProphetModel__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_PROPHETSERVICE = _descriptor.ServiceDescriptor(
  name='ProphetService',
  full_name='net.livemood.bdc.prophet.proto.ProphetService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=76,
  serialized_end=194,
  methods=[
  _descriptor.MethodDescriptor(
    name='forecast',
    full_name='net.livemood.bdc.prophet.proto.ProphetService.forecast',
    index=0,
    containing_service=None,
    input_type=ProphetModel__pb2._PROPHETREQUEST,
    output_type=ProphetModel__pb2._RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PROPHETSERVICE)

DESCRIPTOR.services_by_name['ProphetService'] = _PROPHETSERVICE

ProphetService = service_reflection.GeneratedServiceType('ProphetService', (_service.Service,), dict(
  DESCRIPTOR = _PROPHETSERVICE,
  __module__ = 'ProphetService_pb2'
  ))

ProphetService_Stub = service_reflection.GeneratedServiceStubType('ProphetService_Stub', (ProphetService,), dict(
  DESCRIPTOR = _PROPHETSERVICE,
  __module__ = 'ProphetService_pb2'
  ))


# @@protoc_insertion_point(module_scope)
